server:
  port: 8083
spring:
  application:
    name: common
  profiles:
    include: dev
  #flyway相关配置
  flyway:
    #是否开启flyway
    enabled: true
    #迁移脚本的路径
    locations: classpath:db/migration
    #检查迁移脚本的位置是否存在
    #check-location: true
    #当迁移时发现目标schema非空，而且带有没有元数据的表时，是否自动执行基准迁移，默认false.
    #baseline-on-migrate: true
    #baseline-description对执行迁移时基准版本的描述.
    #baseline-on-migrate当迁移时发现目标schema非空，而且带有没有元数据的表时，是否自动执行基准迁移，默认false.
    #baseline-version开始执行基准迁移时对现有的schema的版本打标签，默认值为1.
    #check-location检查迁移脚本的位置是否存在，默认false.
    #clean-on-validation-error当发现校验错误时是否自动调用clean，默认false.
    #enabled是否开启flywary，默认true.
    #encoding设置迁移时的编码，默认UTF-8.
    #ignore-failed-future-migration当读取元数据表时是否忽略错误的迁移，默认false.
    #init-sqls当初始化好连接时要执行的SQL.
    #locations迁移脚本的位置，默认db/migration.
    #out-of-order是否允许无序的迁移，默认false.
    #password目标数据库的密码.
    #placeholder-prefix设置每个placeholder的前缀，默认${.
    #placeholder-replacementplaceholders是否要被替换，默认true.
    #placeholder-suffix设置每个placeholder的后缀，默认}.
    #placeholders.[placeholder name]设置placeholder的value
    #schemas设定需要flywary迁移的schema，大小写敏感，默认为连接默认的schema.
    #sql-migration-prefix迁移文件的前缀，默认为V.
    #sql-migration-separator迁移脚本的文件名分隔符，默认__
    #sql-migration-suffix迁移脚本的后缀，默认为.sql
    #tableflyway使用的元数据表名，默认为schema_version
    #target迁移时使用的目标版本，默认为latest version
    #url迁移时使用的JDBC URL，如果没有指定的话，将使用配置的主数据源
    #user迁移数据库的用户名
    #validate-on-migrate迁移时是否校验，默认为true.