server:
  port: 8001
spring:
  application:
    name: spring-cloud-gateway-server
  cloud:
    gateway:
      routes:
        - id: user-router
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: email-router
          uri: http://localhost:8082
          predicates:
            - Path=/email/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: spring-cloud-gateway-server