server:
  port: 8003
spring:
  cloud:
    config:
      server:
        default-application-name: server-config
        git:
          uri: https://gitee.com/BetterEveryDay/thoughtworks-homework.git
          search-paths: config
          username: 200525112@qq.com
          password: wanghanwei1102
          default-label: master
      label: master
  profiles:
    active: git

